# Gateway服务配置
# DataID: gateway-service-dev.yml
# Group: GATEWAY_GROUP
# 说明: 网关服务的主要配置，支持动态刷新

server:
  port: 8080

# 启用actuator端点用于调试和监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# 日志配置 - 支持动态调整
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.cloudDemo.gateway: INFO
    org.springframework.cloud.loadbalancer: WARN
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.route: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Spring Cloud Gateway配置
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      # 全局过滤器配置
      default-filters:
        - AddResponseHeader=X-Response-Server, gateway-service
        - AddResponseHeader=X-Response-Time, ${timestamp}
      # 发现定位器配置
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# 认证白名单配置
gateway:
  auth:
    skip-paths:
      - /api/user/login
      - /api/user/register
      - /api/user/list
      - /api/order/list
      - /admin/nacos/**
      - /actuator/**
      - /favicon.ico
  # 限流配置
  rate-limit:
    enabled: true
    default-burst-capacity: 100
    default-replenish-rate: 10
