# Nacos配置中心 - Gateway主配置
# Data ID: gateway-service-dev.yml
# Group: GATEWAY_GROUP
# 命名空间: public

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 使用默认的public命名空间，不指定namespace
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
          lower-case-service-id: true # 服务名小写
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: user-service-cb
                fallbackUri: forward:/fallback/user-service
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
        # 订单服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: order-service-cb
                fallbackUri: forward:/fallback/order-service
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

# 熔断器配置
resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      order-service-cb:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      user-service-cb:
        timeout-duration: 10s
      order-service-cb:
        timeout-duration: 10s

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.cloudDemo.gateway: DEBUG
    io.github.resilience4j: DEBUG
