# Nacos配置中心 - Gateway生产环境配置
# Data ID: gateway-service-prod.yml
# Group: GATEWAY_GROUP
# 命名空间: public

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        # 使用默认的public命名空间，不指定namespace
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 生产环境路由配置
        - id: user-service-prod
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: user-service-cb
                fallbackUri: forward:/fallback/user-service
            - name: Retry
              args:
                retries: 2  # 生产环境减少重试次数
                methods: GET
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@redisRateLimiter}"
                key-resolver: "#{@ipKeyResolver}"
        - id: order-service-prod
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: order-service-cb
                fallbackUri: forward:/fallback/order-service
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "https://*.yourdomain.com"  # 生产环境限制域名
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true

# 生产环境熔断器配置 - 更严格
resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30  # 更严格的失败率
        wait-duration-in-open-state: 60s  # 更长的等待时间
        permitted-number-of-calls-in-half-open-state: 5
      order-service-cb:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 5
  timelimiter:
    instances:
      user-service-cb:
        timeout-duration: 5s  # 生产环境更短的超时时间
      order-service-cb:
        timeout-duration: 5s

# 生产环境日志配置 - 减少调试日志
logging:
  level:
    org.springframework.cloud.gateway: WARN
    com.cloudDemo.gateway: INFO
    io.github.resilience4j: WARN
