server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: default
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: properties
        namespace: public
        group: DEFAULT_GROUP
        # 指定配置文件名，对应Nacos中的DataID
        name: gateway-service
        # 启用配置自动刷新
        refresh-enabled: true

# 日志配置 - 减少控制台输出
logging:
  level:
    root: WARN
    com.cloudDemo: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.web: WARN
    org.springframework.cloud.loadbalancer: WARN
    reactor.netty: WARN
    io.netty: WARN
    com.alibaba.nacos: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
