server:
  port: 8080

# 本地保留最基本的配置，其他配置从Nacos获取
spring:
  application:
    name: gateway-service

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 本地仅保留最基础的日志配置，详细配置在Nacos中
logging:
  level:
    root: INFO
    com.cloudDemo.gateway: DEBUG
